name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore JoeShook.FusionCache.Playground.Core.sln
    - name: Build
      run: dotnet build JoeShook.FusionCache.Playground.Core.sln --no-restore
    - name: Test
      run: dotnet test JoeShook.FusionCache.Playground.Core.sln --no-build --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: ./TestResults/coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: 141e4a826a0a2f46dad85ccf3213a894
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"
